export const CBF_SET_CHECKBOX = 'CBF_SET_CHECKBOX';
export const CBF_UNSET_CHECKBOX = 'CBF_UNSET_CHECKBOX';

export const TGS_SET_ACTIVE_TOGGLE = 'TGS_SET_ACTIVE_TOGGLE';

export const TXT_INPUT_SET_MESSAGE = 'TXT_INPUT_SET_MESSAGE';

export const SELECT_SET_VALUE = 'SELECT_SET_VALUE';
